version: '3.7'

services:  

  nodered:
    build: .
    restart: always
    ports:
     - "2880:1880"
    volumes:
     - ./examples:/data
     - ./examples-rules:/examples-rules
#     - ./settings.js:/home/node-red/settings.js
    environment:
     - FLOWS=/data/flows.json
